### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by minqi-source** [cristianrubioa/extract_trajectory#1]

**Comment by minqi-source** [comment]
First of all, thank you for open source.
I have a question. if a rosbag file didn't contain **nav_msgs/Odometry messages**，Is there any other way to plot his trajectory？

**Comment by cristianrubioa** [comment]
Hi :) @minqi-source 

You can also do it with ```geometry_msgs/PoseStamped``` ```geometry_msgs/TransformStamped``` ```geometry_msgs/PoseWithCovarianceStamped``` topics or  TF messages.

**Comment by minqi-source** [comment]
> Hi :) @minqi-source
> 
> You can also do it with `geometry_msgs/PoseStamped` `geometry_msgs/TransformStamped` `geometry_msgs/PoseWithCovarianceStamped` topics or TF messages.

I get it .thanks !
