### ISSUE TITLE
I have a new problem

### ISSUE THREAD

**Issue by minqi-source** [cristianrubioa/extract_trajectory#2]

**Comment by cristianrubioa** [comment]
Hi @minqi-source 
Try to send the trajectory file you got. 
What are you using for handling, evaluating and comparing the trajectory output?

**Comment by minqi-source** [comment]
> Hi @minqi-source
> Try to send the trajectory file you got.
> What are you using for handling, evaluating and comparing the trajectory output?

I use **evo** to evaluate trajectory.Attached are three track files

**lidarcoord_pose_dcc01_tum_format.csv** is derived from the truth trajectory of the Mulran data set(dcc01/global_pose.csv)
**trajectory.txt** comes from the same data set, and it's the trajectory that was used to build the map(by lego-loam algorithm， **trajectory.txt** build by your tools )


[trajectoryfiles.tar.gz](https://github.com/cristianrubioa/extract_trajectory/files/6284851/trajectoryfiles.tar.gz)
Looking forward to your reply
